spring:
  datasource:
    url: jdbc:h2:mem:database
    username: sa
  jpa:
    open-in-view: false

toss:
  payments:
    base-url: https://api.tosspayments.com
    widget-secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    payment-approve-url: /v1/payments/confirm
    payment-check-url: /v1/payments/{paymentKey}
    payment-cancel-url: /v1/payments/{paymentKey}/check

http-client:
  connect-timeout-millis: 5000
  read-timeout-millis: 5000

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /api-docs.html
    tags-sorter: alpha
    operations-sorter: method
    defaultModelsExpandDepth: 0
