spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:database
    username: sa
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  profiles:
    active: local
toss:
  payments:
    base-url: https://api.tosspayments.com
    widget-secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    payment-approve-url: /v1/payments/confirm
    payment-check-url: /v1/payments/{paymentKey}
    payment-cancel-url: /v1/payments/{paymentKey}/check
http-client:
  connect-timeout-millis: 5000
  read-timeout-millis: 5000
springdoc:
  swagger-ui:
    path: /api-docs.html
    tags-sorter: alpha
